spring:
  application:
    name: mscloudgateway
#  Habilita o localizador de microsericos com caixa baixa
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8081/realms/msrealm"

server:
  port: 8080

#Cadastrando o gateway no eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-user:95wkcq1P@localhost:8761/eureka
